import { capitalReport, type Snapshot } from "@vandlabs/data";
import { CostForm } from "./cost-form";
import { money } from "../lib/format";
export function CapitalView({data}:{data:Snapshot}) {
  if(!data.capabilities?.includes("capital:read"))return <section className="panel"><h1>Capital access restricted</h1><p>Your account needs capital-read permission to view stock economics.</p></section>;
  const report=capitalReport(data.vehicles,data.costs??[],data.sales??[]);
  return <><div className="page-head"><p className="eyebrow">Recorded inventory economics</p><h1>Capital & acquisition age</h1><p className="muted">Verified operator records and explicit assumptions. Missing costs remain unknown.</p></div>
    <section className="metrics"><article className="metric-card"><span>Recorded active capital</span><strong>{money(report.recordedCapital)}</strong><small>{report.coveredVehicles}/{report.activeVehicles} unsold vehicles covered</small></article><article className="metric-card"><span>Capital aged 90+ days</span><strong>{money(report.agedCapital)}</strong><small>Recorded cost basis; no predicted loss</small></article><article className="metric-card"><span>Missing cost records</span><strong>{report.uncoveredVehicles}</strong></article><article className="metric-card"><span>Recorded sale contribution</span><strong>{money(report.realizedContribution)}</strong><small>{report.saleCostCoverage} verified sales with recorded costs</small></article></section>
    <section className="panel"><h2>Evidence & assumptions</h2>{report.assumptions.map(a=><p className="notice" key={a}>{a}</p>)}</section>
    <section className="panel table-panel"><div className="table-scroll"><table><thead><tr><th>Vehicle</th><th>Acquisition age</th><th>Cost basis</th><th>Holding estimate</th><th>Asking spread / sale contribution</th><th>Review priority</th><th>Cost record</th></tr></thead><tbody>{report.rows.map(row=>{const vehicle=data.vehicles.find(v=>v.id===row.vehicleId)!,cost=data.costs?.find(c=>c.vehicleId===row.vehicleId);return <tr key={vehicle.id}><td>{vehicle.make} {vehicle.model}<small>{vehicle.stockId}</small></td><td>{row.ageDays===null?"Unknown":`${row.ageDays} days`}</td><td>{row.costBasis===null?"Unknown":money(row.costBasis)}</td><td>{row.holdingEstimate===null?"Unknown":money(row.holdingEstimate)}</td><td>{row.askingSpread===null?"Unknown":money(row.askingSpread)}<small>{row.recordedContribution===null?"No matched sale/cost record":`Sale: ${money(row.recordedContribution)}`}</small></td><td>{row.priority}</td><td>{data.capabilities?.includes("capital:write")?<CostForm vehicleId={vehicle.id} record={cost}/>:"Read only"}{cost?<small>{cost.reference} · v{cost.version}<br/>Recorded by {cost.recordedBy}</small>:null}</td></tr>;})}</tbody></table></div></section>
    <section className="panel"><h2>Cost change history</h2>{data.costHistory?.length?data.costHistory.map(c=><p key={c.id}>{data.vehicles.find(v=>v.id===c.vehicleId)?.stockId} · v{c.after.version} · {c.after.recordedBy} · {c.after.recordedAt}<br/><small>{c.before?`Amended v${c.before.version}`:"First recorded cost"} · {c.after.reference}</small></p>):<p>No cost records entered. Reference vehicles do not include invented acquisition costs.</p>}</section>
  </>;
}
