import Link from "next/link";
import { inventoryInsights, type Snapshot } from "@vandlabs/data";
import { InventoryMatcher } from "./inventory-matcher";
export function IntelligenceView({data}:{data:Snapshot}) {
  const report=inventoryInsights(data);
  return <><div className="page-head"><p className="eyebrow">Inventory intelligence · {report.version}</p><h1>Dealer priorities, with evidence.</h1><p className="muted">Deterministic decision support from recorded stock and activity. {new Date(report.asOf).toLocaleString("en-IN")}</p></div>
    <div className="metrics"><article className="metric-card"><span>Overdue follow-ups</span><strong>{report.briefing.overdueTasks.length}</strong></article><article className="metric-card"><span>Missing next action</span><strong>{report.briefing.missingNextAction.length}</strong></article><article className="metric-card"><span>Stock data issues</span><strong>{report.dataQuality.withIssues}</strong></article><article className="metric-card"><span>Cost coverage</span><strong>{report.coverage.vehicleCosts}/{report.dataQuality.total}</strong><small>Recorded costs visible to this account</small></article></div>
    <div className="detail-layout"><section className="panel"><h2>Daily dealer briefing</h2><div className="stack-list">{report.briefing.overdueTasks.map(t=><Link href={`/leads/${t.leadId}`} className="list-row" key={t.taskId}><strong>Overdue: {t.owner}</strong><span>{new Date(t.dueAt).toLocaleString("en-IN")}</span></Link>)}{report.briefing.missingNextAction.map(l=><Link href={`/leads/${l.leadId}`} className="list-row" key={l.leadId}><strong>Set next action</strong><span>{l.owner}</span></Link>)}</div>{!report.briefing.overdueTasks.length&&!report.briefing.missingNextAction.length?<p>No follow-up exceptions recorded.</p>:null}</section><section className="panel"><h2>Coverage & boundaries</h2>{report.unavailable.map(item=><p key={item} className="notice">{item}</p>)}<p className="notice">Record age is time since the stock record was created. It is not acquisition age or evidence of dead stock. Rescue candidates require human consent review; no message is sent.</p></section></div>
    <InventoryMatcher vehicles={data.vehicles.map(v=>({id:v.id,make:v.make,model:v.model,price:v.price,fuelType:v.fuelType,transmission:v.transmission,availabilityStatus:v.availabilityStatus,publishStatus:v.publishStatus}))}/>
    <section className="panel table-panel"><h2>Inventory evidence</h2><div className="table-scroll"><table><thead><tr><th>Vehicle</th><th>Record age</th><th>Views / enquiries</th><th>Price changes</th><th>Data quality</th></tr></thead><tbody>{report.vehicles.map(row=>{const v=data.vehicles.find(v=>v.id===row.vehicleId)!;return <tr key={v.id}><td>{v.make} {v.model}<small>{v.stockId}</small></td><td>{row.recordAgeDays===null?"Unknown":`${row.recordAgeDays} days`}</td><td>{row.views} / {row.enquiries}</td><td>{row.priceChanges.length}<small>{row.priceChanges.map(c=>`₹${c.before.price} → ₹${c.after.price}`).join("; ")}</small></td><td>{row.issues.join("; ")||"Required fields present"}</td></tr>;})}</tbody></table></div></section>
  </>;
}
