import { test, expect } from "@playwright/test";
const command="http://127.0.0.1:3001/command";
test("connected browser journey: enquiry, ownership, visit, confirmed sale and delisting", async ({page,request},info)=> {
  const vehicle=info.project.name==="mobile"?{id:"veh-10",slug:"mercedes-a200-2023",query:"A-Class"}:{id:"veh-9",slug:"bmw-x1-18d-2024",query:"X1"};
  await page.goto("/inventory");
  await page.getByPlaceholder("BMW, SUV, automatic...").fill(vehicle.query);
  await expect(page.locator(`a[href="/vehicles/${vehicle.slug}"]`).first()).toBeVisible();
  await page.locator(`a[href="/vehicles/${vehicle.slug}"]`).first().click();
  await page.goto(`/vehicles/${vehicle.slug}?utm_source=playwright&utm_campaign=connected-demo`);
  await page.getByLabel("Name",{exact:true}).fill(`Connected buyer ${info.project.name}`);
  await page.getByLabel("Phone",{exact:true}).fill("+91 90000 00100");
  await page.getByLabel("I want to").selectOption("test_drive");
  const response=page.waitForResponse(r=>r.url().endsWith("/api/leads")&&r.request().method()==="POST");
  await page.getByRole("button",{name:"Send request"}).click();
  const created=await response;expect(created.status()).toBe(201);const {leadId}=await created.json();
  await expect(page.getByText("We have the context.")).toBeVisible();
  await page.goto(`${command}/leads/${leadId}`);
  await page.getByLabel("Pipeline stage").selectOption("qualified");
  await page.getByLabel("Lead owner").selectOption("Maya");
  await page.getByLabel("Internal note").fill("Budget and visit confirmed by staff.");
  await page.getByRole("button",{name:"Save changes"}).click();
  await expect(page.getByRole("status",{name:"Lead update status"})).toHaveText("Saved");
  await page.getByLabel("Visit type").selectOption("test_drive");
  await page.getByLabel("Confirmed visit time").fill("2030-01-15T11:00");
  await page.getByRole("button",{name:"Schedule appointment",exact:true}).click();
  await expect(page.getByLabel("Visit status",{exact:true})).toBeVisible();
  await page.getByLabel("Visit status",{exact:true}).selectOption("completed");
  await expect.poll(async()=>{const r=await request.get(`${command}/api/snapshot`);return (await r.json()).data.appointments.find((a:{leadId:string})=>a.leadId===leadId)?.status;}).toBe("completed");
  await page.getByLabel("Verified sale price (INR)").fill("4700000");
  await page.getByLabel("Actual sale time").fill("2026-01-01T10:00");
  await page.getByLabel("I verified this sale").check();
  const saleResponse=page.waitForResponse(r=>r.url().endsWith(`/leads/${leadId}/sales`));
  await page.getByRole("button",{name:"Confirm sale",exact:true}).click();
  expect((await saleResponse).status()).toBe(201);
  await expect(page.getByText(/Confirmed sale:/)).toBeVisible();
  await expect(page.locator(".stage.large")).toHaveText("Won");
  await page.reload();await expect(page.getByText(/Confirmed sale:/)).toBeVisible();
  const snapshot=await (await request.get(`${command}/api/snapshot`)).json();
  const lead=snapshot.data.leads.find((l:{id:string})=>l.id===leadId);
  expect(lead.vehicleId).toBe(vehicle.id);expect(lead.source).toBe("playwright");expect(lead.campaign).toBe("connected-demo");expect(lead.assignedTo).toBe("Maya");
  expect(snapshot.data.sales.some((s:{leadId:string;amount:number})=>s.leadId===leadId&&s.amount===4700000)).toBeTruthy();
  expect(snapshot.data.tasks.filter((t:{leadId:string})=>t.leadId===leadId).every((t:{completed:boolean})=>t.completed)).toBeTruthy();
  const retry=await request.post(`${command}/api/leads/${leadId}/sales`,{data:{amount:4700000,soldAt:"2026-01-01T10:00:00Z"}});expect(retry.status()).toBe(201);
  const inventory=await (await request.get("/api/vehicles")).json();expect(inventory.data.some((v:{id:string})=>v.id===vehicle.id)).toBeFalsy();
  const unavailable=await request.post("/api/leads",{data:{name:"Late enquiry",phone:"123",vehicleId:vehicle.id}});expect(unavailable.status()).toBe(400);
  await page.goto(`${command}/analytics`);await expect(page.getByText("Confirmed sales",{exact:true})).toBeVisible();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth)).toBeFalsy();
  await page.screenshot({path:info.outputPath("connected-sale-report.png"),fullPage:true});
});

test("inventory edit propagates to website with history",async({page,request})=> {
  const s=await (await request.get(`${command}/api/snapshot`)).json();const vehicle=s.data.vehicles.find((v:{id:string})=>v.id==="veh-13");
  await page.goto(`${command}/inventory`);
  const row=page.locator("tr").filter({has:page.getByLabel(`Price ${vehicle.stockId}`,{exact:true})});
  await row.getByLabel(`Price ${vehicle.stockId}`,{exact:true}).fill(String(vehicle.price+100));
  await row.getByRole("button",{name:"Save inventory"}).click();await expect(row.getByRole("status")).toHaveText("Saved");
  const response=await request.get("/api/vehicles");const inventory=await response.json();expect(inventory.data.find((v:{id:string})=>v.id==="veh-13").price).toBe(vehicle.price+100);
  const history=(await (await request.get(`${command}/api/snapshot`)).json()).data.inventoryHistory;
  expect(history.some((h:{vehicleId:string;after:{price:number}})=>h.vehicleId==="veh-13"&&h.after.price===vehicle.price+100)).toBeTruthy();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth)).toBeFalsy();
});

test("inventory intelligence exposes coverage and exact matching",async({page})=> {
  await page.goto(`${command}/intelligence`);
  await expect(page.getByRole("heading",{name:"Dealer priorities, with evidence."})).toBeVisible();
  await page.getByLabel("Maximum budget (INR)").fill("1");
  await expect(page.getByText("No current vehicles meet these constraints. Ask a salesperson for alternatives.")).toBeVisible();
  await expect(page.getByText("Capital and profit: cost ledger is not configured")).toBeVisible();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth)).toBeFalsy();
});
