import { test, expect } from "@playwright/test";
const api="http://127.0.0.1:3001/command/api";
test("staff enter a draft, review details and publish to the owned website",async({page,request},info)=> {
  const stockId=`INTAKE-${info.project.name.toUpperCase()}`;
  await page.goto("http://127.0.0.1:3001/command/inventory");
  await page.getByText("Enter a vehicle",{exact:true}).click();
  const form=page.locator("form").filter({has:page.getByRole("button",{name:"Save draft vehicle",exact:true})});
  await expect(form.getByRole("button")).toBeEnabled();
  for(const [name,value] of Object.entries({stockId,make:"Honda",model:"City",variant:"ZX",bodyType:"Sedan",exteriorColor:"White",interiorColor:"Black",year:"2022",price:"1200000",mileage:"25000"}))await form.locator(`[name="${name}"]`).fill(value);
  await form.getByRole("button").click();await expect(page.getByRole("status").filter({hasText:`Draft saved: ${stockId}`})).toBeVisible();
  const snapshot=(await (await request.get(`${api}/snapshot`)).json()).data;
  const vehicle=snapshot.vehicles.find((v:{stockId:string})=>v.stockId===stockId);
  expect(vehicle.publishStatus).toBe("draft");expect((await (await request.get("/api/vehicles")).json()).data.some((v:{id:string})=>v.id===vehicle.id)).toBeFalsy();
  const row=page.getByRole("row").filter({has:page.getByRole("cell",{name:stockId,exact:true})});
  await row.getByText("Edit vehicle details",{exact:true}).click();
  const detailForm=row.locator("form").filter({has:page.getByRole("button",{name:"Save vehicle details",exact:true})});
  await detailForm.locator('[name="variant"]').fill("ZX reviewed");
  await detailForm.locator('[name="imageUrl"]').fill("https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800");
  await detailForm.getByRole("button").click();await expect(row.getByRole("status")).toHaveText("Saved");
  await expect(row.getByText("ZX reviewed",{exact:true})).toBeVisible();
  const statusForm=row.locator("form").filter({has:page.getByRole("button",{name:"Save inventory",exact:true})});
  await statusForm.locator('[name="publication"]').selectOption("published");await statusForm.getByRole("button").click();
  await expect.poll(async()=> (await (await request.get("/api/vehicles")).json()).data.some((v:{id:string})=>v.id===vehicle.id)).toBeTruthy();
  await page.goto(`/vehicles/${vehicle.slug}`);await expect(page.getByRole("heading",{name:"Honda City",exact:true})).toBeVisible();await expect(page.getByText("ZX reviewed",{exact:true})).toBeVisible();
});
test("CSV preview creates nothing; reviewed batches persist once with duplicate and scope protection",async({page,request},info)=> {
  const stockId=`CSV-${info.project.name.toUpperCase()}`;
  const csv='stockId,make,model,variant,year,price,mileage,fuelType,transmission,ownership,bodyType,condition,exteriorColor,interiorColor\n'+`${stockId},Honda,City,"ZX, Premium",2022,1200000,25000,petrol,automatic,1,Sedan,good,White,Black\n`;
  await page.goto("http://127.0.0.1:3001/command/inventory");await page.getByText("Import CSV",{exact:true}).click();
  const textarea=page.getByLabel("CSV contents");await expect(textarea).toBeEnabled();await textarea.fill(csv);
  await page.getByRole("button",{name:"Preview import",exact:true}).click();await expect(page.getByRole("button",{name:"Import 1 drafts",exact:true})).toBeVisible();
  let snapshot=(await (await request.get(`${api}/snapshot`)).json()).data;
  expect(snapshot.vehicles.some((v:{stockId:string})=>v.stockId===stockId)).toBeFalsy();
  await page.getByRole("button",{name:"Import 1 drafts",exact:true}).click();await expect(page.getByRole("status").filter({hasText:"Imported 1 draft vehicles."})).toBeVisible();
  snapshot=(await (await request.get(`${api}/snapshot`)).json()).data;const vehicle=snapshot.vehicles.find((v:{stockId:string})=>v.stockId===stockId);expect(vehicle.variant).toBe("ZX, Premium");expect(vehicle.publishStatus).toBe("draft");
  expect(snapshot.inventoryHistory.filter((h:{vehicleId:string;action:string})=>h.vehicleId===vehicle.id&&h.action==="created")).toHaveLength(1);
  const body={dealershipId:vehicle.dealershipId,locationId:vehicle.locationId,csv,mode:"commit"};
  const repeated=await request.post(`${api}/vehicles/import`,{data:body});expect(repeated.status()).toBe(400);expect((await repeated.json()).issues[0].field).toBe("stockId");
  expect((await request.post(`${api}/vehicles/import`,{data:{...body,locationId:"forged"}})).status()).toBe(403);
  expect((await request.post(`${api}/vehicles/import`,{data:{...body,csv:"x".repeat(1000001)}})).status()).toBe(400);
  await page.screenshot({path:`test-results/inventory-intake-${info.project.name}.png`,fullPage:true});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy();
});
