import { test } from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { PGlite } from "@electric-sql/pglite";
import { postgresStore, RecordNotFound, ConflictError } from "../../packages/data/src/index";
import { tenantTransaction, type SqlPool } from "../../packages/data/src/postgres";
import { AuthorizationError, type AuthenticatedPrincipal, type Vehicle } from "../../packages/contracts/src/index";
import { vehicles } from "../../packages/demo-data/src/index";

test("real PostgreSQL engine: isolation, shared records, atomic audit/task writes and rollback",async()=>{
 const db=new PGlite();await db.waitReady;
 try{
  for(const name of ["0001_core_tenant_schema.sql","0002_ecosystem_records.sql","0003_sales_inventory_history.sql","0004_stock_costs.sql"]){const sql=await readFile(`infra/database/migrations/${name}`,"utf8");await db.exec(sql.replace("CREATE EXTENSION IF NOT EXISTS pgcrypto;",""));}
  const a="11111111-1111-4111-a111-111111111111",b="22222222-2222-4222-a222-222222222222";
  const dealer="33333333-3333-4333-a333-333333333333",location="44444444-4444-4444-a444-444444444444",otherLocation="55555555-5555-4555-a555-555555555555",vehicleId="66666666-6666-4666-a666-666666666666";
  await db.query("INSERT INTO organizations(id,tenant_id,name) VALUES($1,$1,'A'),($2,$2,'B')",[a,b]);
  await db.query("INSERT INTO dealerships(id,tenant_id,organization_id,name,brand_name) VALUES($1,$2,$2,'A','A')",[dealer,a]);
  for(const id of [location,otherLocation])await db.query("INSERT INTO locations(id,tenant_id,dealership_id,name,city,state,phone) VALUES($1,$2,$3,'Location','City','State','123')",[id,a,dealer]);
  const vehicle:Vehicle={...vehicles[0],id:vehicleId,tenantId:a,dealershipId:dealer,locationId:location};
  await db.query("INSERT INTO vehicles(id,tenant_id,dealership_id,location_id,slug,stock_id,payload,publish_status,availability_status) VALUES($1,$2,$3,$4,'car','stock',$5,'published','available')",[vehicleId,a,dealer,location,vehicle]);
  const ruleId="77777777-7777-4777-a777-777777777777";
  await db.query("INSERT INTO automation_rules(id,tenant_id,payload) VALUES($1,$2,$3)",[ruleId,a,{id:ruleId,tenantId:a,name:"Qualified follow-up",enabled:true,trigger:"stage_changed",stages:["qualified"],delayMinutes:15,taskTitle:"Automated follow-up",ownerFallback:"Staff",priority:"normal",channel:"internal_task",requiresWhatsappConsent:false}]);
  await db.exec(await readFile("infra/database/application-role.sql","utf8"));
  const pool:SqlPool={async connect(){return {async query(sql,values){const result=await db.query<Record<string,unknown>>(sql,values);return {rows:result.rows};},release(){}};}};
  await assert.rejects(tenantTransaction(pool,a,async()=>true),/must not bypass RLS/);
  await db.exec("SET ROLE vandlabs_app");
  const store=postgresStore(pool);
  const p:AuthenticatedPrincipal={userId:"staff",tenantId:a,dealershipIds:[dealer],locationIds:[location],capabilities:["lead:read","lead:write","task:write","inventory:read","inventory:write","analytics:read","capital:read","capital:write"]};
  const created=await store.createLead({tenantId:a,dealershipId:dealer,locationId:location,vehicleId,vehicleIds:[vehicleId],name:"Buyer",phone:"123",channel:"web",intent:"enquiry",source:"website",consent:{whatsapp:false,marketing:false}});
  const leadId=created.lead.id;
  const one=await store.snapshot(p);assert.equal(one.leads[0].id,leadId);assert.equal(one.vehicles.length,1);
  const updated=await store.patchLead(p,leadId,{stage:"qualified",notes:"Confirmed"});assert.equal(updated.activity.length,2);
  const task=await store.createTask(p,leadId,{title:"Call",owner:"Staff",dueAt:"2030-01-01T10:00:00Z",priority:"high"});
  await store.completeTask(p,task.data.id,true);
  const snapshot=await store.snapshot(p);assert.equal(snapshot.tasks.find(t=>t.id===task.data.id)?.completed,true);assert.equal(snapshot.activities.length,4);
  assert.equal(snapshot.runs.filter(r=>r.outcome==="created").length,1);
  await store.patchLead(p,leadId,{stage:"contacted"});await store.patchLead(p,leadId,{stage:"qualified"});
  const repeated=await store.snapshot(p);assert.equal(repeated.tasks.filter(t=>t.origin==="automation").length,1);assert.equal(repeated.runs.filter(r=>r.outcome==="skipped_duplicate").length,1);
  const broken:SqlPool={async connect(){const c=await pool.connect();return {release:()=>c.release(),async query(sql,values){if(sql.startsWith("INSERT INTO lead_activities"))throw new Error("audit failure");return c.query(sql,values);}};}};
  await assert.rejects(postgresStore(broken).patchLead(p,leadId,{stage:"won"}),/audit failure/);
  assert.equal((await store.snapshot(p)).leads[0].stage,"qualified");
  const other={...p,tenantId:b};assert.equal((await store.snapshot(other)).leads.length,0);
  await assert.rejects(store.patchLead(other,leadId,{stage:"won"}),RecordNotFound);
  await assert.rejects(store.createTask({...p,locationIds:[otherLocation]},leadId,{title:"Denied",owner:"Staff",dueAt:"2030-01-01",priority:"normal"}),AuthorizationError);
  const appointment=await store.scheduleAppointment(p,leadId,{type:"test_drive",scheduledAt:"2030-01-15T11:00:00Z"});
  await store.setAppointmentStatus(p,appointment.data.id,"completed");
  assert.equal((await store.snapshot(p)).appointments[0].status,"completed");
  await assert.rejects(store.scheduleAppointment({...p,locationIds:[otherLocation]},leadId,{type:"test_drive",scheduledAt:"2030-01-15T11:00:00Z"}),AuthorizationError);
  await assert.rejects(store.setAppointmentStatus(other,appointment.data.id,"completed"),RecordNotFound);
  const saleInput={amount:5800000,soldAt:"2026-01-01T10:00:00Z"};
  await assert.rejects(postgresStore(broken).confirmSale(p,leadId,saleInput),/audit failure/);
  assert.equal((await store.snapshot(p)).sales?.length,0);
  assert.equal((await store.inventory(a,dealer))[0].availabilityStatus,"available");
  await assert.rejects(store.confirmSale({...p,capabilities:["lead:write"]},leadId,saleInput),AuthorizationError);
  await assert.rejects(store.confirmSale(other,leadId,saleInput),RecordNotFound);
  const sale=await store.confirmSale(p,leadId,saleInput);
  const closed=await store.snapshot(p);
  assert.equal(closed.sales?.length,1);assert.equal(closed.leads[0].stage,"won");assert.ok(closed.tasks.every(t=>t.completed));
  assert.equal((await store.inventory(a,dealer)).length,0);
  assert.equal((await store.confirmSale(p,leadId,saleInput)).data.id,sale.data.id);
  await assert.rejects(store.confirmSale(p,leadId,{...saleInput,amount:1}),ConflictError);
  await assert.rejects(store.updateVehicle(p,vehicleId,{price:100,availabilityStatus:"available",publishStatus:"published"},0),ConflictError);
  assert.equal((await store.snapshot(other)).sales?.length,0);
  await store.updateVehicle(p,vehicleId,{price:100,availabilityStatus:"sold",publishStatus:"published", ...{slug:"forged",tenantId:b}},closed.vehicles[0].version??0);
  assert.equal((await store.inventory(a,dealer))[0].availabilityStatus,"sold");
  assert.equal((await store.inventory(a,dealer))[0].slug,"car");
  await assert.rejects(store.createLead({tenantId:a,dealershipId:dealer,locationId:location,vehicleId,vehicleIds:[vehicleId],name:"Buyer",phone:"123",channel:"web",intent:"enquiry",source:"website",consent:{whatsapp:false,marketing:false}}),/unavailable/);
  await assert.rejects(tenantTransaction(pool,a,async c=>{await c.query("UPDATE leads SET stage='won' WHERE id=$1",[leadId]);throw new Error("simulated failure");}),/simulated failure/);
  assert.equal((await store.snapshot(p)).leads[0].stage,"won");
  const intake={stockId:"NEW-1",make:"Honda",model:"City",variant:"ZX",year:2022,price:1200000,mileage:25000,fuelType:"petrol",transmission:"automatic",ownership:1,bodyType:"Sedan",condition:"good",exteriorColor:"White",interiorColor:"Black"};
  const count=(await store.snapshot(p)).vehicles.length;
  const preview=await store.createInventoryBatch(p,dealer,location,[intake],{preview:true});
  assert.equal(preview.preview,true);assert.equal((await store.snapshot(p)).vehicles.length,count);
  await assert.rejects(store.createInventoryBatch({...p,capabilities:["inventory:read"]},dealer,location,[intake]),AuthorizationError);
  await assert.rejects(store.createInventoryBatch(p,dealer,otherLocation,[intake]),AuthorizationError);
  await assert.rejects(store.createInventoryBatch(other,dealer,location,[intake]),/Unknown destination/);
  const auditBroken:SqlPool={async connect(){const c=await pool.connect();return {release:()=>c.release(),async query(sql,values){if(sql.startsWith("INSERT INTO inventory_history"))throw new Error("inventory audit failure");return c.query(sql,values);}};}};
  await assert.rejects(postgresStore(auditBroken).createInventoryBatch(p,dealer,location,[intake]),/inventory audit failure/);
  assert.equal((await store.snapshot(p)).vehicles.length,count);
  const imported=await store.createInventoryBatch(p,dealer,location,[intake,{...intake,stockId:"NEW-2"}]);
  assert.equal(imported.vehicles.length,2);assert.equal(imported.vehicles[0].publishStatus,"draft");assert.equal(imported.vehicles[0].tenantId,a);
  assert.equal((await store.inventory(a,dealer)).some(v=>v.stockId==="NEW-1"),false);
  assert.equal((await store.snapshot(p)).inventoryHistory?.filter(h=>h.batchId===imported.batchId&&h.action==="created").length,2);
  await assert.rejects(store.createInventoryBatch(p,dealer,location,[{...intake,stockId:"NEW-3"},{...intake,stockId:"new-1"}]),/validation failed/);
  assert.equal((await store.snapshot(p)).vehicles.length,count+2);
  await assert.rejects(store.updateVehicle(p,imported.vehicles[0].id,{price:1200000,publishStatus:"published",availabilityStatus:"available"},0),/Publication requires/);
  const edited=await store.updateVehicleDetails(p,imported.vehicles[0].id,{...intake,model:"City Hybrid",imageUrl:"https://images.example.com/stock.jpg"},0);
  assert.equal(edited.slug,imported.vehicles[0].slug);assert.equal(edited.media.length,1);assert.equal(edited.publishStatus,"draft");
  await assert.rejects(store.updateVehicleDetails(p,edited.id,{...intake,stockId:"CHANGED"},1),/cannot be changed/);
  await assert.rejects(store.updateVehicleDetails(other,edited.id,intake,0),RecordNotFound);
  await store.updateVehicle(p,edited.id,{price:1200000,publishStatus:"published",availabilityStatus:"available"},1);
  assert.equal((await store.inventory(a,dealer)).find(v=>v.id===edited.id)?.model,"City Hybrid");
  await assert.rejects(store.updateVehicleDetails(p,edited.id,intake,2),/requires imagery/);
  await assert.rejects(store.updateVehicleDetails(p,edited.id,{...intake,imageUrl:"https://images.example.com/stock.jpg"},1),ConflictError);
  await assert.rejects(store.updateVehicle(p,edited.id,{price:1,publishStatus:"published",availabilityStatus:"available"},1),ConflictError);
  const costs={acquiredOn:"2025-01-01",purchasePrice:1000000,reconditioningCost:25000,transferCost:5000,otherCost:0,dailyHoldingCost:null,reference:"TEST-INVOICE-1"};
  await assert.rejects(store.saveStockCost({...p,capabilities:p.capabilities.filter(c=>c!=="capital:write")},edited.id,costs,0),AuthorizationError);
  await assert.rejects(store.saveStockCost({...p,locationIds:[otherLocation]},edited.id,costs,0),AuthorizationError);
  await assert.rejects(store.saveStockCost(other,edited.id,costs,0),RecordNotFound);
  const costAuditBroken:SqlPool={async connect(){const c=await pool.connect();return {release:()=>c.release(),async query(sql,values){if(sql.startsWith("INSERT INTO stock_cost_history"))throw new Error("cost audit failure");return c.query(sql,values);}};}};
  await assert.rejects(postgresStore(costAuditBroken).saveStockCost(p,edited.id,costs,0),/cost audit failure/);
  assert.equal((await store.snapshot(p)).costs?.length,0);
  const recorded=await store.saveStockCost(p,edited.id,costs,0);assert.equal(recorded.version,1);
  await assert.rejects(store.saveStockCost(p,edited.id,costs,0),ConflictError);
  const amended=await store.saveStockCost(p,edited.id,{...costs,otherCost:1000},1);assert.equal(amended.version,2);
  assert.equal((await store.snapshot(p)).costHistory?.length,2);
  const ordinary=await store.snapshot({...p,capabilities:p.capabilities.filter(c=>c!=="capital:read")});assert.equal(ordinary.costs,undefined);assert.equal(ordinary.costHistory,undefined);
  assert.equal((await store.snapshot(other)).costs?.length,0);
  await assert.rejects(store.saveStockCost(p,vehicleId,{...costs,acquiredOn:"2026-01-02"},0),/cannot follow/);
  const unset=await db.query("SELECT nullif(current_setting('app.tenant_id',true),'') AS tenant");assert.equal(unset.rows[0].tenant,null);
  assert.equal((await db.query("SELECT id FROM leads")).rows.length,0);
 }finally{await db.close();}
});
