import React, { useEffect, useRef, useState } from "react";
import { createRoot } from "react-dom/client";
import { invoke } from "@tauri-apps/api/core";
import type { Lead, Task, Vehicle, LeadStage, AuthenticatedPrincipal } from "@vandlabs/contracts";
import "./style.css";
interface Config { apiOrigin:string; cognitoDomain:string; clientId:string }
interface Dashboard { data:{leads:Lead[];tasks:Task[];vehicles:Vehicle[]};principal:AuthenticatedPrincipal;metrics:{available:number;leads:number;wins:number} }
const stages:LeadStage[]=["new","contacted","qualified","appointment","visited","test_drive","negotiation","won","lost","nurture"];
function App(){
 const [config,setConfig]=useState<Config>(()=>{try{return JSON.parse(localStorage.getItem("engine.connection")||"null")||{apiOrigin:"",cognitoDomain:"",clientId:""};}catch{return {apiOrigin:"",cognitoDomain:"",clientId:""};}});
 const [dashboard,setDashboard]=useState<Dashboard|null>(null),[section,setSection]=useState("Today"),[busy,setBusy]=useState(false),[error,setError]=useState(""),[selected,setSelected]=useState<Lead|null>(null);
 async function load(){const result=await invoke<Dashboard>("api_request",{config,path:"/snapshot",method:"GET",body:null});setDashboard(result);setSelected(l=>result.data.leads.find(x=>x.id===l?.id)||null);}
 async function perform(action:()=>Promise<unknown>){setBusy(true);setError("");try{await action();}catch(e){setError(String(e));}finally{setBusy(false);}}
 const initialConfig=useRef(config);
 useEffect(()=>{const c=initialConfig.current;if(!c.apiOrigin||!c.clientId||!c.cognitoDomain)return;let mounted=true;
  setBusy(true);invoke("restore_session",{config:c}).then(()=>invoke<Dashboard>("api_request",{config:c,path:"/snapshot",method:"GET",body:null})).then(result=>{if(mounted)setDashboard(result);}).catch(e=>{if(mounted)setError(String(e));}).finally(()=>{if(mounted)setBusy(false);});
  return()=>{mounted=false;};
 },[]);

 async function login(){localStorage.setItem("engine.connection",JSON.stringify(config));await invoke("login",{config});await load();}
 async function mutate(path:string,body:unknown,method="PATCH"){await invoke("api_request",{config,path,method,body});await load();}
 const todayTasks=dashboard?.data.tasks.filter(t=>!t.completed)||[];
 return <div className="shell"><aside><div className="brand">VANDLABS<span>Automobile Engine</span></div><nav>{["Today","Inventory","Leads","Follow-ups"].map(s=><button className={section===s?"active":""} key={s} onClick={()=>{setSection(s);setSelected(null);}}>{s}</button>)}</nav><small>One dealership. Every surface.</small></aside><main><header><div><p className="eyebrow">DEALER WORKSPACE</p><h1>{section}</h1></div>{dashboard&&<div className="actions"><button disabled={busy} onClick={()=>void perform(load)}>Refresh</button><button disabled={busy} onClick={()=>void perform(async()=>{await invoke("logout",{config});setDashboard(null);})}>Sign out</button></div>}</header>
 {error&&<p role="alert" className="error">{error}</p>}{busy&&<p role="status">Working…</p>}
 {!dashboard?<section className="panel connect"><h2>Your operating system, connected.</h2><p>Connect to your dealership deployment, then sign in using your staff account in the system browser.</p><label>Command Center origin<input type="url" placeholder="https://operations.example.com" value={config.apiOrigin} onChange={e=>setConfig({...config,apiOrigin:e.target.value})}/></label><label>Cognito sign-in domain<input type="url" placeholder="https://your-domain.auth.region.amazoncognito.com" value={config.cognitoDomain} onChange={e=>setConfig({...config,cognitoDomain:e.target.value})}/></label><label>Desktop app client ID<input value={config.clientId} onChange={e=>setConfig({...config,clientId:e.target.value})}/></label><button className="primary" disabled={busy} onClick={()=>void perform(login)}>Sign in securely</button><small>Credentials stay in your operating system’s secure credential store.</small></section>:<>
 {section==="Today"&&<><div className="metrics">{[["Available vehicles",dashboard.metrics.available],["Captured leads",dashboard.metrics.leads],["Open follow-ups",todayTasks.length],["Recorded wins",dashboard.metrics.wins]].map(([label,value])=><article key={label}><span>{label}</span><strong>{value}</strong></article>)}</div><section className="panel"><h2>Move the next opportunity forward.</h2>{dashboard.data.leads.slice(0,6).map(l=><button className="row" key={l.id} onClick={()=>{setSection("Leads");setSelected(l);}}><span><strong>{l.name}</strong><small>{l.phone}</small></span><span>{l.stage.replaceAll("_"," ")}</span></button>)}{!dashboard.data.leads.length&&<p>No leads yet. Website enquiries appear here automatically.</p>}</section></>}
 {section==="Inventory"&&<div className="cards">{dashboard.data.vehicles.map(v=><article className="panel" key={v.id}><p className="eyebrow">{v.stockId} · {v.year}</p><h2>{v.make} {v.model}</h2><p>{v.variant} · {v.mileage.toLocaleString()} km</p><strong className="price">₹{v.price.toLocaleString("en-IN")}</strong><p>{v.availabilityStatus} · {v.publishStatus}</p>{dashboard.principal.capabilities.includes("inventory:write")&&<button disabled={busy} onClick={()=>void perform(()=>mutate(`/vehicles/${v.id}`,{price:v.price,availabilityStatus:v.availabilityStatus==="sold"?"available":"sold",publishStatus:v.publishStatus}))}>{v.availabilityStatus==="sold"?"Mark available":"Mark sold"}</button>}</article>)}</div>}
 {section==="Leads"&&!selected&&<section className="panel">{dashboard.data.leads.map(l=><button className="row" key={l.id} onClick={()=>setSelected(l)}><span><strong>{l.name}</strong><small>{l.phone} · {l.source}</small></span><span>{l.stage}</span></button>)}</section>}
 {section==="Leads"&&selected&&<section className="panel"><button onClick={()=>setSelected(null)}>Back to leads</button><h2>{selected.name}</h2><p>{selected.phone} · {selected.intent}</p><label>Pipeline stage<select value={selected.stage} disabled={busy||!dashboard.principal.capabilities.includes("lead:write")} onChange={e=>void perform(()=>mutate(`/leads/${selected.id}`,{stage:e.target.value}))}>{stages.map(s=><option key={s} value={s}>{s.replaceAll("_"," ")}</option>)}</select></label><p>{selected.notes||"No internal note yet."}</p>{dashboard.principal.capabilities.includes("task:write")&&<form onSubmit={e=>{e.preventDefault();const form=new FormData(e.currentTarget);void perform(()=>mutate(`/leads/${selected.id}/tasks`,{title:form.get("title"),owner:form.get("owner"),dueAt:new Date(String(form.get("due"))).toISOString(),priority:"normal"},"POST"));}}><h3>Schedule follow-up</h3><label>Action<input name="title" required maxLength={160}/></label><label>Owner<input name="owner" required maxLength={100} defaultValue={selected.assignedTo}/></label><label>Due<input type="datetime-local" name="due" required/></label><button disabled={busy}>Schedule</button></form>}</section>}
 {section==="Follow-ups"&&<section className="panel">{dashboard.data.tasks.map(t=><div className="row" key={t.id}><span><strong>{t.title}</strong><small>{t.owner} · {new Date(t.dueAt).toLocaleString()}</small></span><button disabled={busy||!dashboard.principal.capabilities.includes("task:write")} onClick={()=>void perform(()=>mutate(`/tasks/${t.id}`,{completed:!t.completed}))}>{t.completed?"Reopen":"Complete"}</button></div>)}</section>}
 </>}
 </main></div>;
}
createRoot(document.getElementById("root")!).render(<React.StrictMode><App/></React.StrictMode>);
