import Link from "next/link";
import { getDesktopRelease, releaseRepository } from "../../lib/desktop-release";
import { dealershipService } from "../../lib/services";
import { DesktopTour } from "../../components/desktop-tour";
import { SpotlightCard } from "../../components/spotlight-card";

export const metadata = { title: "Download Automobile Engine", description: "Explore the connected VandLabs workspace, download Windows/macOS installers, and learn how to connect your dealership." };
export default async function Download() {
  const [release, inventory] = await Promise.all([getDesktopRelease(), dealershipService.inventory()]);
  const vehicles = inventory.map(({ id, slug, make, model, year, price, availabilityStatus }) => ({ id, slug, make, model, year, price, availabilityStatus }));
  return <main className="shell section connected-page desktop-page">
    <div className="download-head" data-reveal><span className="app-logo" aria-hidden="true">A<span>↗</span></span><p className="eyebrow">VandLabs Automobile Engine</p><h1>A workspace<br />that moves with you.</h1><p className="lede">Your inventory. Your conversations. Your next move.<br />Connected, wherever your day takes you.</p><div className="actions"><a href="#installers" className="button primary">Get the desktop app ↓</a><a href="#product-tour" className="rolling-link">Take a closer look ↗</a></div><span className="download-version">{release ? `Development build · ${release.tag}` : "Installer release pending"}</span></div>
    <div id="product-tour"><DesktopTour vehicles={vehicles} /></div>
    <section className="desktop-benefits" data-reveal><SpotlightCard><span className="benefit-icon" aria-hidden="true">⇄</span><h3>One source of truth.</h3><p>Your website and dealer workspace connect to the same inventory. An activated dealership keeps its records together.</p><Link href="/inventory" className="rolling-link">Explore the collection ↗</Link></SpotlightCard><SpotlightCard><span className="benefit-icon" aria-hidden="true">⌘</span><h3>Built around your day.</h3><p>Inventory, leads, follow-ups, appointments and recorded outcomes, together in the dealer workspace.</p><a href="#product-tour" className="rolling-link">Explore the tour ↗</a></SpotlightCard><SpotlightCard><span className="benefit-icon" aria-hidden="true">↗</span><h3>Your role. Your access.</h3><p>The native app signs in through your system browser. Staff permissions control the records and actions you can use.</p><Link href="/contact" className="rolling-link">Ask about access ↗</Link></SpotlightCard></section>
    <section id="installers" className="installers-section" data-reveal><div className="sectionhead"><div><p className="eyebrow">Choose your computer</p><h2>Make room for<br />a better workspace.</h2></div><p className="subtle">Windows x64. Universal macOS.<br />An online workspace, connected by your team.</p></div><div className="download-cards">{(["windows", "mac"] as const).map(platform => {
      const asset = release?.assets[platform];
      return <article className="download-card" key={platform}><span className="platform-mark" aria-hidden="true">{platform === "windows" ? "⊞" : "⌘"}</span><p className="eyebrow">{platform === "windows" ? "WINDOWS / X64" : "MACOS / UNIVERSAL"}</p><h2>{platform === "windows" ? "Made for your PC." : "At home on your Mac."}</h2><p>{platform === "windows" ? "Windows installer for the dealer workspace. WebView2 is handled by the installer when required." : "A universal app for Apple silicon and Intel Macs, packaged in a disk image."}</p>{asset ? <a className="button primary" href={`/api/downloads/${platform}`}>Download for {platform === "windows" ? "Windows" : "macOS"} <span aria-hidden="true">↓</span></a> : <span className="download-version">Available after the release pipeline passes</span>}{asset && <small>{(asset.size / 1024 / 1024).toFixed(1)} MB · {asset.name}</small>}{asset?.sha256 && <details><summary>Verify download checksum</summary><p className="checksum">SHA-256: {asset.sha256}</p></details>}<small>Development distribution. Installers are currently unsigned; macOS notarization and installed-device acceptance are pending.</small></article>;
    })}</div></section>
    <section className="download-steps" aria-label="Get started" data-reveal><article><span>01 / INSTALL</span><h3>Choose your computer.</h3><p>Download the installer for your operating system and open the app.</p></article><article><span>02 / CONNECT</span><h3>Enter your workspace URL.</h3><p>The app discovers your dealership’s public sign-in settings. Your administrator activates the shared workspace first.</p></article><article><span>03 / SIGN IN</span><h3>Pick up your day.</h3><p>Sign in through your system browser. Your role controls the records and actions you can access.</p></article></section>
    <section className="faq-section" data-reveal><p className="eyebrow">Before you download</p><h2>A few helpful answers.</h2><div className="faq-list"><details><summary>Can I use the app offline?</summary><p>No. The dealership workspace is online. An active backend and an internet connection are required.</p></details><details><summary>What do I need to sign in?</summary><p>An active HTTPS workspace URL from your administrator and an assigned staff account. The app opens your system browser for secure sign-in.</p></details><details><summary>Is this a customer-ready release?</summary><p>These are unsigned development installers. Signing, macOS notarization, installed-device acceptance and live backend activation remain pending.</p></details></div></section>
    <section className="discovery-note" data-reveal><div><p className="eyebrow">Pick up where you left off</p><h2>The showroom comes with you.</h2><p>Explore vehicles on the website or ask the team about access to the dealer workspace.</p></div><Link className="button primary" href="/inventory">Explore inventory ↗</Link><a className="button" href={release?.url ?? `https://github.com/${releaseRepository}/releases`}>Release details ↗</a></section>
  </main>;
}
