import Link from "next/link";
import type { PlatformTenant } from "@vandlabs/contracts";
import { runtimeReadiness } from "@vandlabs/data";
import { StaffManager } from "./staff-manager";

export function PlatformView({tenants,section="overview"}:{tenants:PlatformTenant[];section?:string}) {
  const readiness=runtimeReadiness("platform"),reference=process.env.DATA_MODE!=="aurora";
  const totals=tenants.reduce((a,t)=>({vehicles:a.vehicles+t.counts.vehicles,leads:a.leads+t.counts.leads,openTasks:a.openTasks+t.counts.openTasks,sales:a.sales+t.counts.sales,published:a.published+t.counts.publishedVehicles}),{vehicles:0,leads:0,openTasks:0,sales:0,published:0});
  const label:Record<string,string>={overview:"The network, clearly.",dealerships:"Dealerships",organizations:"Organizations & scopes",onboarding:"Onboarding",health:"Platform health",staff:"Staff & permissions",audit:"Privileged activity",integrations:"Integration readiness",features:"Rollout & entitlements"};
  return <main><div className="page-head"><p className="eyebrow">{reference?"Local reference ecosystem":"Shared ecosystem"}</p><h1>{label[section]}</h1><p className="lede">{reference?"Reference records and new local operations share one atomic store.":"Organization records and operational counts come from the shared tenant-isolated PostgreSQL database."}</p></div>
    {section==="overview"?<section className="metrics">{[["Organizations",tenants.length],["Vehicles",totals.vehicles],["Published",totals.published],["Leads",totals.leads],["Open tasks",totals.openTasks],["Recorded sales",totals.sales]].map(([name,value])=><article key={name}><span>{name}</span><strong>{value}</strong></article>)}</section>:null}
    {["overview","dealerships","organizations"].includes(section)?<section className="panel table-panel"><h2>Authorized organizations</h2><div className="table-scroll"><table><thead><tr><th>Organization</th><th>Dealership</th><th>Locations</th><th>Stock</th><th>Leads</th></tr></thead><tbody>{tenants.flatMap(t=>t.dealerships.map(d=><tr key={d.id}><td><strong>{t.organization}</strong><small>{t.tenantId}</small></td><td>{d.name}</td><td>{d.locations.map(l=>l.name+" · "+l.city).join(", ")}</td><td>{t.counts.vehicles} across organization</td><td>{t.counts.leads} across organization</td></tr>))}</tbody></table></div><Link href="/staff">Manage staff access →</Link></section>:null}
    {["health","onboarding"].includes(section)?<><section className="panel"><h2>{readiness.ready?"Configuration ready for connection checks":"Setup still required"}</h2><p>Configuration checks do not certify connectivity or live sign-in. The protected readiness API performs tenant-isolated database reads.</p><div className="stack">{readiness.checks.map(c=><div className="row" key={c.key}><div><strong>{c.key}</strong><small>{c.detail}</small></div><span className={"pill "+(c.ready?"complete":"ready")}>{c.ready?"configured":"missing"}</span></div>)}</div><a href="/platform/api/readiness">Run database readiness check</a></section><section className="panel"><h2>Independent launch acceptance</h2><p>Cognito login and MFA, native installation, backup restore, monitoring and provider delivery need separate verification. This screen makes no claim about their acceptance.</p></section></>:null}
    {section==="staff"?tenants.map(t=><StaffManager key={t.tenantId} tenant={{tenantId:t.tenantId,organization:t.organization,dealerships:t.dealerships,staff:t.staff}}/>):null}
    {section==="audit"?<section className="panel table-panel"><h2>Persisted staff-access audit</h2><div className="table-scroll"><table><thead><tr><th>Time</th><th>Actor</th><th>Action</th><th>Subject</th><th>Tenant</th></tr></thead><tbody>{tenants.flatMap(t=>t.audit.map(a=><tr key={a.id}><td>{new Date(a.occurredAt).toISOString()}</td><td>{a.actor}</td><td>{a.action}</td><td>{a.subject}</td><td>{t.organization}</td></tr>))}</tbody></table></div>{!tenants.some(t=>t.audit.length)?<p>No staff access changes recorded yet.</p>:null}</section>:null}
    {section==="integrations"?<section className="panel"><h2>Connected boundaries</h2><p>Inventory, enquiries, CRM, appointments, costs, sales and staff permissions use the selected shared adapter. WhatsApp currently supports click-to-chat; outbound provider delivery, licensed market feeds and advanced AI are pending provider setup and implementation.</p></section>:null}
    {section==="features"?<section className="panel"><h2>Managed release configuration</h2><p>Purchased entitlements and experience flags are supplied through the dealership configuration. Runtime flag editing and billing are not enabled in this release. Deployment configuration must be reviewed before changing customer access.</p></section>:null}
    {!tenants.length?<section className="panel"><p>No organizations are provisioned in this administrator’s explicit tenant scope.</p></section>:null}
  </main>;
}
